kind: pipeline
type: kubernetes
name: hugo-pipeline

steps:
- name: build-hugo
  image: klakegg/hugo:latest
  commands:
  - cd posts  # ←Hugoディレクトリに移動♠
  - hugo --minify
  - ls -la public/  # ←ビルド確認♧

- name: create-docker-context
  image: alpine:latest
  commands:
  - cp -r posts/public ./public  # ←ルートにpublicコピー♥
  - ls -la public/

- name: build-docker
  image: plugins/docker
  settings:
    dockerfile: Dockerfile  # ←ルートのDockerfile想定♠
    repo: wasuken/tech_blog
    tags: 
    - latest
    - ${DRONE_COMMIT_SHA:0:8}
    registory: false

- name: deploy
  image: alpine:latest
  commands:
  - echo "Hugo build complete!"
  - echo "Built files in public/ directory"

# Drone側でイメージビルド→push→kubectl更新
- name: update-deployment
  image: bitnami/kubectl
  commands:
  - kubectl set image deployment/hugo-site hugo=wasuken/hugo:${DRONE_BUILD_NUMBER}
