kind: pipeline
type: kubernetes
name: hugo-pipeline

volumes:
- name: shared-volume
  temp: {}

steps:
- name: build-hugo
  image: klakegg/hugo:latest
  volumes:
  - name: shared-volume
    path: /shared
  commands:
  - cd posts
  - hugo
  - cp -r public /shared/

- name: docker-build
  image: plugins/docker
  volumes:
  - name: shared-volume
    path: /shared
  settings:
    registry: ghcr.io
    repo: ghcr.io/wasuken/tech_blog
    username:
      from_secret: github_username
    password:
      from_secret: github_token
    tags:
    - latest
    - "${DRONE_COMMIT_SHA:0:8}"
  commands:
    - cp -r /shared/public ./public

- name: deploy-to-k3s
  image: bitnami/kubectl
  environment:
    KUBECONFIG:
      from_secret: kubeconfig
  commands:
    - kubectl set image deployment/hugo-site hugo=ghcr.io/wasuken/tech_blog:${DRONE_COMMIT_SHA:0:8}
    - kubectl rollout status deployment/hugo-site

- name: deploy-complete
  image: alpine:latest
  commands:
  - echo "Hugo build complete!"
  - echo "Image pushed successfully"
