baseURL = 'https://wasutech.dev'
languageCode = 'ja'
title = '怠惰技術ブログ'
theme = 'PaperMod'

enableRobotsTXT = true
enableEmoji = true

ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]

[frontmatter]
date = [":filename", ":default"]

[params]
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  assets.favicon = "/favicon.png"
  ShowShareButtons = true

[params.homeInfoParams]
  Title = "記事一覧"
  Content = "技術メモを残していきます"

[[menu.main]]
  name = "トップ"
  url = "https://wasutech.dev"
  weight = 5
[[menu.main]]
  name = "アーカイブ"
  url = "/archives/"
  weight = 10
[[menu.main]]
  name = "検索"
  url = "/search/"
  weight = 20
[[menu.main]]
  name = "タグ"
  url = "/tags/"
  weight = 30
[[menu.main]]
  name = "RSS"
  url = "/index.xml"
  weight = 40

[outputs]
  home = ["HTML", "RSS", "JSON"]
