baseURL = '/'
languageCode = 'ja'
title = '怠惰技術ブログ'
theme = 'PaperMod'

enableRobotsTXT = true
enableEmoji = true

ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]

[params]
  ShowShareButtons = false
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  assets.favicon = "/favicon.png"

[params.homeInfoParams]
  Title = "記事一覧"
  Content = "技術メモを残していきます"

[[menu.main]]
  name = "トップ"
  url = "https://wasutech.dev"
  weight = 1
[[menu.main]]
  name = "アーカイブ"
  url = "/archives/"
  weight = 10
[[menu.main]]
  name = "検索"
  url = "/search/"
  weight = 20
[[menu.main]]
  name = "タグ"
  url = "/tags/"
  weight = 30

[outputs]
  home = ["HTML", "RSS", "JSON"]
